[1m[31mERROR   [0m applitools.selenium.command_executor:command_executor.py:169 Re-raising an error received from SDK server: USDKFailure('Request "openEyes" that was sent to the address "[POST]https://eyesapi.applitools.com/api/sessions/running" failed due to unexpected status Unauthorized(401)', '    at Object.afterResponse (C:\\snapshot\\eyes-universal\\node_modules\\@applitools\\core-base\\dist\\server\\req-eyes.js:101:23)\n    at C:\\snapshot\\eyes-universal\\node_modules\\@applitools\\req\\dist\\req.js:95:103\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async req (C:\\snapshot\\eyes-universal\\node_modules\\@applitools\\req\\dist\\req.js:163:20)\n    at async Object.openEyes (C:\\snapshot\\eyes-universal\\node_modules\\@applitools\\core-base\\dist\\server\\requests.js:54:26)\n    at async openEyes (C:\\snapshot\\eyes-universal\\node_modules\\@applitools\\core-base\\dist\\open-eyes.js:62:30)\n    at async C:\\snapshot\\eyes-universal\\node_modules\\@applitools\\core\\dist\\ufg\\core.js:50:38')